#!/bin/sh
uci batch <<EOF
	delete ucitrack.@bypass[-1]
	add ucitrack bypass
	set ucitrack.@bypass[-1].init=bypass
	commit ucitrack
	delete firewall.bypass
	set firewall.bypass=include
	set firewall.bypass.type=script
	set firewall.bypass.path=/var/etc/bypass.include
	set firewall.bypass.reload=1
	commit firewall
EOF

chmod +x /etc/init.d/bypass /usr/share/bypass/* >/dev/null 2>&1
rm -rf /tmp/luci-*
#[ -s "/etc/config/bypass" ] || /etc/init.d/bypass reset
sed -i "s/option type 'vmess'/option type 'v2ray'\n\toption v2ray_protocol 'vmess'/g" /etc/config/bypass
sed -i "s/option type 'vless'/option type 'v2ray'\n\toption v2ray_protocol 'vless'/g" /etc/config/bypass
sed -i "s/option encrypt_method_v2ray_ss/option encrypt_method_ss/g" /etc/config/bypass
sed -i "s/option xtls/option tls/g" /etc/config/bypass
sed -i "/option vless_flow/d" /etc/config/bypass
sed -i "/option fingerprint 'disable'/d" /etc/config/bypass

exit 0
