#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@netspeedlimit[-1]
	add ucitrack netspeedlimit
	set ucitrack.@netspeedlimit[-1].init=netspeedlimit
	commit ucitrack
EOF


rm -f /tmp/luci-indexcache
exit 0

