#!/bin/sh /etc/rc.common

START=19
USE_PROCD=1

boot() {
	. /lib/config/uci.sh
	# disabled until mwan3 start runs so hotplug scripts
	# do not start prematurely
	uci_toggle_state mwan3 globals enabled "0"
	rc_procd start_service
}

# FIXME
# fd 1000 is an inherited lock file descriptor for preventing concurrent
# init script executions. Close it here to prevent the mwan3 daemon from
# inheriting it further to avoid holding the lock indefinitely.

reload_service() {
	/usr/sbin/mwan3 restart
}

start_service() {
	[ -n "${mwan3_boot}" ] && return 0
	/usr/sbin/mwan3 start
}

stop_service() {
	/usr/sbin/mwan3 stop
}

service_triggers() {
	procd_add_reload_trigger 'mwan3'
}
