#!/bin/sh
chmod +x /etc/init.d/netwizard 2>/dev/null
[ "x$(uci -q get netwizard.netwizard.display)" = "x1"  ] &&  echo ' ' > /etc/config/netwizarded || rm -rf /etc/config/netwizarded
 
rm -f /tmp/luci-indexcache
exit 0
