#!/bin/sh
chmod +x /etc/init.d/netwizard 2>/dev/null
[ "x$(uci -q get netwizard.netwizard.display)" = "x1"  ] &&  echo ' ' > /etc/config/netwizarded || rm -rf /etc/config/netwizarded

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@netwizard[-1]
	add ucitrack netwizard
	set ucitrack.@netwizard[-1].init="netwizard"
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
