#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@netwizard[-1]
	add ucitrack netwizard
	set ucitrack.@netwizard[-1].init=netwizard
	commit ucitrack
EOF

chmod +x /etc/init.d/netwizard 2>/dev/null
rm -f /tmp/luci-indexcache
exit 0
