# LuCI qcatku Theme
# Copyright 2019-2023 sirpdboy <sirpdboy@qq.com>
# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

PKG_NAME:=luci-theme-qcatku
LUCI_DEPENDS:=+curl +jsonfilter
PKG_VERSION:=1.1.2
PKG_RELEASE:=20230220
LUCI_TITLE:=qcatku Theme

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
