
# Copyright (C) 2019-2023 sirpdboy
# http://www.github.com/sirpdboy/luci-theme-kucat
# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

THEME_NAME:=kucat
THEME_TITLE:=Kucat Theme
PKG_VERSION:=1.1.1
PKG_RELEASE:=20230220

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
