#!/bin/sh /etc/rc.common
START=99
STOP=10

boot() {
    [ "$(uci get network.wan.up)" -eq 1 ] && start
}

reload() {
	/usr/lib/ddns/dynamic_dns_updater.sh -- reload
	return 0
}

restart() {
	/usr/lib/ddns/dynamic_dns_updater.sh -- stop
	sleep 1	# give time to shutdown
	/usr/lib/ddns/dynamic_dns_updater.sh -- start
}

start() {
	/usr/lib/ddns/dynamic_dns_updater.sh -- start
}

stop() {
	/usr/lib/ddns/dynamic_dns_updater.sh -- stop
	return 0
}
