#!/bin/sh /etc/rc.common

#
# Copyright (C) 2020-2023  sirpdboy  <herboy2008@gmail.com> https://github.com/sirpdboy/netspeedtest

# This is free software, licensed under the Apache License, Version 2.0 .
#

START=99
USE_PROCD=1

. /etc/openwrt_release
. /lib/functions/netspeedtest.sh

PROG=/usr/bin/homebox
BINSPEEDTEST='/usr/bin/speedtest'
EXTRA_COMMANDS="nstest"

LOCK=/var/lock/netspeedtest.lock
LOG=/var/log/netspeedtest.log
nstest() {
    TESTMODE=1
    limit_log $LOG 500
    init_log $LOG
    BINTEMP=$(git_bin_handle $TESTMODE)
    [ -x "$BINSPEEDTEST" ] || return
    
    # [ -n `busybox ps -w | grep $BINSPEEDTEST | grep -v grep ` ] && return
    URL=$(speedtest_start $TESTMODE $BINTEMP)
    [ -n "$URL" ] && echo $URL

}

get_config() {
        config_get_bool enabled $1 enabled 1
	config_get_bool logger $1 logger 1
}

homebox_prepare() {
	pgrep -f homebox | xargs kill -9 >/dev/null 2>&1 
	killall homebox
	killall homebox
}

start_service() {
	config_load netspeedtest
        config_foreach get_config netspeedtest
	[ "x$enabled" != "x1" ] && {
	    homebox_prepare 
	   exit 
	}
	procd_open_instance
	procd_set_param command $PROG
	[ "x$logger" == x1 ] && procd_set_param stderr 1
	# procd_set_param respawn
	procd_close_instance
}

service_triggers() {
      procd_add_reload_trigger "netspeedtest"
}
