#!/bin/sh /etc/rc.common

#
# Copyright (C) 2020-2023  sirpdboy  <herboy2008@gmail.com> https://github.com/sirpdboy/netspeedtest

# This is free software, licensed under the Apache License, Version 2.0 .
#

START=99
USE_PROCD=1

. /etc/openwrt_release
. /lib/functions/netspeedtest.sh

PROG=/usr/bin/homebox
BINSPEEDTEST='/usr/bin/speedtest'
EXTRA_COMMANDS="nstest"

LOCK=/var/lock/netspeedtest.lock
LOG=/var/log/netspeedtest.log

nstest() {
    TESTMODE=1
    limit_log $LOG 500
    init_log $LOG
    BINTEMP=$(git_bin_handle $TESTMODE)
    [ -n "$BINTEMP" ] || return
    case $TESTMODE in
    1) 
    echone  "\n  python3-speedtest测速"
    info=$($BINTEMP > $TMP_TEST ) >/dev/null 2>&1
    echone   "\n  测服信息:`cat  $TMP_TEST | grep 'Hosted by'| cut -c10- | awk -F: '{printf $1}'`  延时：`cat  $TMP_TEST | grep 'Hosted by' | awk -F: '{printf $2}'`"
    echone  "\n  下行速率:`cat  $TMP_TEST  | grep 'Download:' |awk -F: '{printf $2}' `  --"
    echone  "--  上行速率:`cat  $TMP_TEST  | grep 'Upload:' |awk -F: '{printf $2}' `"
    echone  "\n  测速结果图片链接:`cat  $TMP_TEST | grep 'results' | cut -c16-`"
    echone  "\n  测试时间: `date +%Y-%m-%d' '%H:%M:%S`"
    echone  "\n  ————————————————————————————\n"
    cat $TMP_TEST | grep 'results:' | cut -c16- > /var/speedtesturl.tmp
    echo -ne "`cat $TMP_TEST | grep 'results:' | cut -c16-`"
     ;;  
    *) 
    echone "\n  ookla-speedtest测速"
    info=$($BINTEMP > $TMP_TEST ) >/dev/null 2>&1
    echone "\n  info:$info ----------------- "
    echone   "\n  测服信息:`cat  $TMP_TEST | grep 'Server'| cut -c10- | awk -F: '{printf $2$3}'`  线路:`cat  $TMP_TEST | grep 'ISP' | awk -F: '{printf $2}' `  延时：`cat  $TMP_TEST | grep 'Latency' | awk -F: '{printf $2}'  | awk -F '(' '{printf $1}'`"
    echone  "\n  下行速率:`cat  $TMP_TEST  | grep 'Download' |awk -F: '{printf $2}'  | awk -F '(' '{printf $1}'`  --"
    echone  "--  上行速率:`cat  $TMP_TEST  | grep 'Upload' |awk -F: '{printf $2}' | awk -F '(' '{printf $1}'`"
    echone  "\n  测速结果图片链接:`cat  $TMP_TEST | grep 'URL' | cut -c15-`"
    echone  "\n  测试时间: `date +%Y-%m-%d' '%H:%M:%S`"
    echone  "\n  ————————————————————————————\n"
    cat $TMP_TEST | grep 'URL' | cut -c15- > /var/speedtesturl.tmp
    echo -ne "`cat $TMP_TEST | grep 'URL' | cut -c15- `"
     ;;  
    esac

}

get_config() {
        config_get_bool enabled $1 enabled 1
	config_get_bool logger $1 logger 1
}

homebox_prepare() {
	pgrep -f homebox | xargs kill -9 >/dev/null 2>&1 
	killall homebox
	killall homebox
}

start_service() {
	config_load netspeedtest
        config_foreach get_config netspeedtest
	[ "x$enabled" != "x1" ] && {
	    homebox_prepare 
	   exit 
	}
	procd_open_instance
	procd_set_param command $PROG
	[ "x$logger" == x1 ] && procd_set_param stderr 1
	# procd_set_param respawn
	procd_close_instance
}

service_triggers() {
      procd_add_reload_trigger "netspeedtest"
}
