#!/bin/sh
[ "$1" = check ] || exit 1
NAME=bypass
T_FILE=/etc/bypass
log(){
	 echo "$(date +'%Y-%m-%d %H:%M:%S') By Check Network  :$*" >> /tmp/log/$NAME.log
}

B=1
while ! curl -so /dev/null -m 3 www.baidu.com;do
   [ $B -ge 20 ]&& /etc/init.d/$NAME stop&& /etc/init.d/$NAME start
   let B++
   log "请检查网络..."
   sleep 2
done
if [ -z "$(uci -q get $NAME.@global[0].global_server)" ];then
/etc/init.d/$NAME start &
elif [ ! -s $T_FILE/china.txt ] || [ ! -s $T_FILE/china_v6.txt ] || [ ! -s $T_FILE/gfw.list ] ;then
	log "Update IP/GFW files."
	/usr/share/$NAME/update --f ;exit 0;
else
	/etc/init.d/$NAME start &
fi
