#!/bin/sh
[ "$1" = check ] || exit 1
NAME=bypass
T_FILE=/etc/bypass
log(){
	 echo "$(date +'%Y-%m-%d %H:%M:%S') By Rules     : $*" >> /tmp/log/$NAME.log
}

while ! curl -so /dev/null -m 3 www.baidu.com;do
	log "请检查网络..."
	sleep 2
done
if [ -z "$(uci -q get $NAME.@global[0].global_server)" ];then
/etc/init.d/$NAME start &
elifif [ ! -s $T_FILE/china.txt ] || [ ! -s $T_FILE/china_v6.txt ] || [ ! -s $T_FILE/gfw.list ] ;then
	log "Rules      :Download IP/GFW files."
	/usr/share/$NAME/update --f ;exit 0;
else
	/etc/init.d/$NAME start &
fi
