log:
  level: info

plugins:

  - tag: lazy_cache
    type: cache
    args:
      size: cache_size
      lazy_cache_ttl: cache_survival_time

  - tag: geosite_cn
    type: domain_set
    args:
      files:
        - "/var/etc/bypass/domains_cn.txt"

  - tag: geoip_cn
    type: ip_set
    args:
      files:
        - "/var/etc/bypass/china.txt"

  - tag: geosite_no_cn
    type: domain_set
    args:
      files:
        - "/var/etc/bypass/gfw.list"

  - tag: forward_xinfeng_udp
    type: forward
    args:
      concurrent: 2
      upstreams:
        - addr: "114.114.114.114"
        - addr: "114.114.115.115"

  - tag: forward_local
    type: forward
    args:
      concurrent: 2
      upstreams:
        - addr: local_dns

  - tag: forward_remote
    type: forward
    args:
      concurrent: 2
      upstreams:
        - addr: remote_dns

  - tag: forward_remote_upstream_ipv6
    type: sequence
    args:
      - exec: $forward_remote

  - tag: forward_remote_upstream
    type: sequence
    args:
      - exec: prefer_ipv4
      - exec: $forward_remote
      - matches: 
         - qtype 28 65
         exec: reject 0

  - tag: has_resp_sequence
    type: sequence
    args:
      - matches: has_resp
        exec: accept

  - tag: query_is_non_local_ip
    type: sequence
    args:
      - exec: $forward_local
      - matches: "!resp_ip $geoip_cn"
        exec: drop_resp


  - tag: query_is_local_domain
    type: sequence
    args:
      - matches: qname $geosite_cn
        exec: $forward_local

  - tag: query_is_no_local_domain
    type: sequence
    args:
      - matches: qname $geosite_no_cn
        exec: $forward_remote_upstream

  - tag: fallback
    type: fallback
    args:
      primary: UNDEFINED
      secondary: forward_remote_upstream
      threshold: 500
      always_standby: true

  - tag: main_sequence
    type: sequence
    args:
        exec: $lazy_cache
      - exec: $query_is_local_domain
      - exec: jump has_resp_sequence
      - exec: $query_is_no_local_domain
      - exec: jump has_resp_sequence
      - exec: $fallback

  - tag: udp_server
    type: udp_server
    args:
      entry: main_sequence
      listen: ":DNS_PORT"

  - tag: tcp_server
    type: tcp_server
    args:
      entry: main_sequence
      listen: ":DNS_PORT"
