#!/usr/bin/lua

local ucursor = require "luci.model.uci".cursor()
local json = require "luci.jsonc"

local datatypes = require "luci.cbi.datatypes"

function is_ipv6(val)
    local str = val
    local address = val:match('%[(.*)%]')
    if address then
        str = address
    end
    if datatypes.ip6addr(str) then
        return true
    end
    return false
end

function get_ipv6_only(val)
    local result = ""
    if is_ipv6(val) then
        result = val
        if val:match('%[(.*)%]') then
            result = val:match('%[(.*)%]')
        end
    end
    return result
end

local server_section = arg[1]
local proto = arg[2]
local local_port = arg[3] or "0"
local socks_port = arg[4] or "0"
local node = ucursor:get_all("bypass", server_section)
local server_host = arg[5] or node.server

local cipher = "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES128-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA:AES128-SHA:AES256-SHA:DES-CBC3-SHA"
local cipher13 = "TLS_AES_128_GCM_SHA256:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_256_GCM_SHA384"

-- if is_ipv6(server_host) then
--    server_host = get_ipv6_only(server_host)
-- end
local server = server_host

local trojan = {
	log_level = 3,
	run_type = (proto == "nat" or proto == "tcp") and "nat" or "client",
	local_addr = "0.0.0.0",
	local_port = tonumber(local_port),
	remote_addr = server,
	remote_port = tonumber(node.server_port),
	udp_timeout = 60,
	password = {node.password},
	ssl = {
		verify = (node.insecure ~= "1") and true or false,
		verify_hostname = (node.insecure ~= "1") and true or false,
		cert = (node.certificate=="1") and node.certpath or "",
		cipher = cipher,
		cipher_tls13 = cipher13,
		sni = node.tls_host or server,
		alpn={"h2","http/1.1"},
		curves = "",
		reuse_session = true,
		session_ticket = false
	},
	tcp = {
		no_delay = true,
		keep_alive = true,
		reuse_port = true,
		fast_open = (node.fast_open == "1") and true or false,
		fast_open_qlen = 20
	}
}
print(json.stringify(trojan, 1))


