#!/bin/sh /etc/rc.common
# Copyright (C) 2017 lean <coolsnowwolf@gmail.com>

START=99

start() {
	rfc=4096
	threads="$(grep -c "processor" "/proc/cpuinfo")"

	sysctl -w net.core.rps_sock_flow_entries="$(( rfc * threads ))"  >/dev/null

	for fileRps in /sys/class/net/eth*/queues/rx-*/rps_cpus
	do
		echo "$threads" > "$fileRps"
	done

	for fileRfc in /sys/class/net/eth*/queues/rx-*/rps_flow_cnt
	do
		echo "$rfc" > "$fileRfc"
	done

	uci set network.@globals[0].packet_steering="1"
	uci commit network
	g=$(dmesg | grep 'DMI:' | awk -F ', BIOS' '{print $1 }' | awk -F ':' '{print $2 }')

	[ -d /tmp/sysinfo ] || mkdir -p /tmp/sysinfo
	echo $g > /tmp/sysinfo/model

	vendor=$(lscpu | grep -m1 "Vendor ID:" | cut -d':' -f 2)
	if [ -z "$vendor" ]; then
	    vendor=$(lscpu | grep -m1 "BIOS Vendor ID:" | cut -d':' -f 2)
	fi

	if [ -z "$vendor" ]; then
	    vendor="GenuineIntel"
	fi
	str1="Default string Default string/Default string"
	str2="Default string Default string"
	str3="Default string"
	rpl="$vendor"

	sed -i -e  -e "s|$str1|$rpl|g" -e "s|$str2|$rpl|g" -e "s|$str3|$rpl|g" -e "s/^[ \t]*//g" /tmp/sysinfo/model
	all_pcis=`lspci | grep -i 'eth' | grep -i 'x550' | cut -d ' ' -f 1`
	all_ifs=`cat /proc/net/dev | grep -i 'eth' | cut -d :  -f 1 | sed 's/^[ \t]*//g'`

	for ifname in ${all_ifs}
	do
		if_pci=`ethtool -i ${ifname} | grep -i 'bus-info' | cut -d : -f 3-`
		if [[ "$all_pcis" =~ "$if_pci" ]]
		then
			ethtool -s ${ifname} advertise 0x1800000001028
		fi
	done
	for i in $(ip address | awk -F ': ' '/eth[0-9]+/ {print $2}' | xargs)
	do
		{
			ethtool -K "$i" rx-checksum on
			ethtool -K "$i" tx-checksum-ip-generic on || {
				ethtool -K "$i" tx-checksum-ipv4 on
				ethtool -K "$i" tx-checksum-ipv6 on
			}
			ethtool -K "$i" tx-scatter-gather on
			ethtool -K "$i" gso on
			ethtool -K "$i" tso off
			ethtool -K "$i" ufo on
		}
	done
} >"/dev/null" 2>&1
