#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org
# Copyright 2022-2023 sirpdboy <herboy2008@gmail.com>


START=98
STOP=15


NAME=eqosplus
LOCK="/var/lock/$NAME.lock"
CR=/etc/crontabs/root

start_instance() {
	 if [ x$(uci get $NAME.@$NAME[0].ifname) = 'x1' ] ;then
 	     dev=`ifconfig | grep "Point-to-Point" | cut -d " " -f1`
 	     [ ! $dev ] && dev=` uci -q get network.wan.ifname ` || dev=` uci -q get network.wan.device ` 
 	     [ ! $dev ] && dev=br-lan
	 else
	      dev=`uci -q get $NAME.@$NAME[0].ifname `
	 fi
	 idlist=`uci show $NAME | grep "enable='1'" | grep "device" | grep -oE '\[.*?\]' | grep -o '[0-9]' `
	 procd_open_instance
	 procd_set_param command /usr/sbin/eqosplusctrl -d $dev -o $idlist
	 procd_set_param respawn
	 procd_set_param stderr 1
	 procd_close_instance
}

eqosplus_start() {
	 if [ "$(grep -c 'option enable .1.' /etc/config/$NAME 2>/dev/null)" -gt "0" ]; then
	    touch $LOCK
	    eqosplus start
	    start_instance
	    (crontab -l ; echo "00 1 * * * /etc/init.d/eqosplus start") | sort - | uniq - | crontab -
	 fi
}

start_service(){
	[ -f $LOCK ] && exit
	stop_service
	eqosplus_start
	rm -f $LOCK
}

stop_service() {
	kill -9 $(busybox ps -w | grep 'eqosplusctrl' | grep -v 'grep' | awk '{print $1}') >/dev/null 2>&1
	sed -i '/eqosplus/d' $CR >/dev/null 2>&1
	rm -f $LOCK 2>/dev/null
	eqosplus stop
}

service_triggers() {
 	 procd_add_reload_trigger 'eqosplus'
}

