#!/bin/sh /etc/rc.common
#
# Copyright (C) 2023 sirpdboy herboy2008@gmail.com
#

START=99
USE_PROCD=1

NAME=nqos
LOCK="/var/lock/$NAME.lock"

_nqos_start() {
	 if [ "$(grep -c 'option enable .1.' /etc/config/$NAME 2>/dev/null)" -gt "0" ]; then
	    if [ x$(uci -q get turboacc.config.sw_flow) = 'x1' ] || [ x$(uci -q get turboacc.config.sfe_flow) = 'x1' ]  ;then
	         uci -q set turboacc.config.sw_flow='0'
	         uci -q set turboacc.config.sfe_flow='0'
		 uci -q set turboacc.config.hw_flow='0'
		 uci commit turboacc
		 /etc/init.d/turboacc restart
	    fi
	    touch $LOCK
	    nqos start
	 fi
}

start(){
	[ -f $LOCK ] && exit
	stop
	_nqos_start
	rm -f $LOCK
}

stop(){
	# kill -9 $(busybox ps -w | grep 'nqos' | grep -v 'grep' | awk '{print $1}') >/dev/null 2>&1
	rm -f $LOCK 2>/dev/null
	nqos stop
}

