#!/bin/sh
# Copyright (C) 2022 jjm2473

if [ ! -f /etc/config/fstab ]; then
    /usr/libexec/blockmount.sh detect 2>/dev/null
fi

uci -q batch <<-EOF >/dev/null
    set system.@system[-1].zonename='Asia/Shanghai'
    set system.@system[-1].timezone='CST-8'
    commit system
EOF

uci set dockerd.globals.data_root=/opt/docker


uci -q batch <<-EOF >/dev/null
    commit dockerd
EOF

uci -q batch <<-EOF >/dev/null
    set luci.apply.rollback=30
    set luci.apply.holdoff=2
    commit luci
EOF


exit 0
