#!/bin/sh /etc/rc.common
#  Copyright 2019-2023 sirpdboy <sirpdboy@qq.com>

START=98
sum=$(grep -c 'theme' /etc/config/advancedplus)
useset=0
for i in $(seq 0 $((sum-1)))
do
    use=$(uci -q get advancedplus.@theme[$i].use )
    if [ x$use = x1 ]; then
	mode=`uci -q get advancedplus.@theme[$i].mode`
	primary=`uci -q get advancedplus.@theme[$i].primary`
	uci set advancedplus.@basic[0].mode=${mode}
	case "$primary" in
		blue)
			uci set advancedplus.@basic[0].primary='#146db3'
			uci set advancedplus.@basic[0].primary_body='#fff'
			uci set advancedplus.@basic[0].primary_rgb='20,109,179'
			uci set advancedplus.@basic[0].primary_rgb_ts='0.2'
			uci set advancedplus.@basic[0].primary_rgbs='205,79,57'
 			[ $mode = dark ] && uci set advancedplus.@basic[0].primary_body='#212d3c'
		;;
		green)
			uci set advancedplus.@basic[0].primary='#1a8361'
			uci set advancedplus.@basic[0].primary_body='#fff'
			uci set advancedplus.@basic[0].primary_rgb='26,131,97'
			uci set advancedplus.@basic[0].primary_rgb_ts='0.2'
			uci set advancedplus.@basic[0].primary_rgbs='225,112,88'
 			[ $mode = dark ] && uci set advancedplus.@basic[0].primary_body='#212d3c'
		;;
		orange)
		
			uci set advancedplus.@basic[0].primary='#a34706'
			uci set advancedplus.@basic[0].primary_body='#fff'
			uci set advancedplus.@basic[0].primary_rgb='163,71,6'
			uci set advancedplus.@basic[0].primary_rgb_ts='0.2'
			uci set advancedplus.@basic[0].primary_rgbs='60,179,113'
 			[ $mode = dark ] && uci set advancedplus.@basic[0].primary_body='#212d3c'
		;;
		red)
			uci set advancedplus.@basic[0].primary='#b3351f'
			uci set advancedplus.@basic[0].primary_body='#fff'
			uci set advancedplus.@basic[0].primary_rgb='143,32,13'
			uci set advancedplus.@basic[0].primary_rgb_ts='0.2'
			uci set advancedplus.@basic[0].primary_rgbs='33,150,243'
 			[ $mode = dark ] && uci set advancedplus.@basic[0].primary_body='#212d3c'
		;;
		*)
			uci set advancedplus.@basic[0].primary=`uci -q get advancedplus.@theme[$i].primary`
			uci set advancedplus.@basic[0].primary_body=`uci -q get advancedplus.@theme[$i].primary_body`
			uci set advancedplus.@basic[0].primary_rgb=`uci -q get advancedplus.@theme[$i].primary_rgb`
			uci set advancedplus.@basic[0].primary_rgbs=`uci -q get advancedplus.@theme[$i].primary_rgbs`
			uci set advancedplus.@basic[0].primary_rgb_ts=`uci -q get advancedplus.@theme[$i].primary_rgb_ts`
 			[ $mode = dark ] && uci set advancedplus.@basic[0].primary_body='#212d3c'
 		;;
	esac
	break
	exit
    fi
done
if [ $useset== 0 ] ; then
	uci set advancedplus.@basic[0].mode='light'
	uci set advancedplus.@basic[0].primary='#4aa185'
	uci set advancedplus.@basic[0].primary_body='#fff'
	uci set advancedplus.@basic[0].primary_rgb='74,161,133'
	uci set advancedplus.@basic[0].primary_rgb_ts='0.2'
	uci set advancedplus.@basic[0].primary_rgbs='225,112,88'
 	[ $mode = dark ] && uci set advancedplus.@basic[0].primary_body='#212d3c'
fi



root() {
   boot=1
}

