#!/bin/sh

# author github@sirpdboy
[ -s "/etc/config/kucat" ] &&kucat='kucat'
[ -s "/etc/config/advancedplus" ] &&kucat='advancedplus'
background="$(uci -q get $kucat.@basic[0].background || echo '0')"
KUCATTMP="/var/kucat_date_${background}.tmp"
BGURL="/www/luci-static/kucat/img/down${background}.jpg"
REBGURL="/luci-static/kucat/img/down${background}.jpg"
DFBGURL="/luci-static/kucat/img/bg1.jpg"
LOCK="/var/lock/kucat_lock_${background}.lock"

curl_bgurl() {
	case "$background" in
	1)
		echo "https://api.upchiu.com/random/api.php"
		;;
	2)
		local ppath="$(curl -s "https://source.unsplash.com/1920x1080/daily?wallpapers" 2>&1 |grep -Eo "photo-\w+-\w+" | head -n1)"
		[ -n "${ppath}" ] && echo "https://images.unsplash.com/${ppath}?fm=jpg&fit=crop&w=1920&h=1080"
		;;

	3)
		local ppath=`curl -s  "https://www.bing.com/HPImageArchive.aspx?format=js&n=1" |jsonfilter -qe '@.images[0].url'`
		[ -n "${ppath}" ] && echo "https://www.bing.com${ppath}"
		;;

	4)
		local i=`awk 'BEGIN{srand();print int(rand()*8)}'`
		local j=`awk 'BEGIN{srand();print int(rand()*200)}'`
		ppath=`curl -s "http://wp.birdpaper.com.cn/intf/search?content=4k&pageno=$j&count=9" | awk -F '\"count\":9' '{print $2}' | awk -F ',\"processTime\"' '{print $1}' | sed 's#,#{#' |  jsonfilter -e "@.list[$i].url"`

		[ -n "${ppath}" ] && echo "$ppath"
		;;

	esac
}

bgurl_down() {
		local bgurl="$(curl_bgurl)"
		if [ -n "$bgurl" ]; then
			rm -rf $BGURL
			curl -kLfsm 3 $bgurl -o $BGURL
			date +%Y%m%d > $KUCATTMP
		fi
	[ -s "$BGURL" ] && echo -ne $REBGURL || echo -ne $DFBGURL
}

check_url() {
checknet=`/usr/bin/wget --spider -qT3 https://www.taobao.com  2>"/dev/null" && echo -ne 1 || echo -ne 0 `
if [ $checknet == 1 ]; then
	if [ -s $KUCATTMP ]; then
		localtime=`cat $KUCATTMP | grep $(date +%Y%m%d) `
		if [ $localtime ]; then
		   if  [ -s $BGURL ] ; then
		        echo -ne $REBGURL 
			return
		   fi
		fi
	fi
	bgurl_down
fi
}
check_url