#!/bin/sh
chmod +x /etc/init.d/kucat
uci -q batch <<-EOF >/dev/null
	delete ucitrack.@kucat[-1]
	add ucitrack kucat
	set ucitrack.@kucat[-1].init=kucat
	commit ucitrack
EOF
[ -s /etc/config/kucat ]  || /etc/init.d/kucat reset
[ -s /usr/lib/lua/luci/view/themes/argon/sysauth.htm ] && sed -i 's,media .. \"\/b,resource .. \"\/b,g' /usr/lib/lua/luci/view/themes/argon/sysauth.htm
rm -f /tmp/luci-indexcache
exit 0

