#!/bin/sh /etc/rc.common
. /usr/share/libubox/jshn.sh
. /lib/functions.sh

START=96
USE_PROCD=1
OAFD_BIN="/usr/bin/oafd"
FEATURE_FILE="/tmp/feature.cfg"
CLASS_FILE="/tmp/app_class.txt"
add_crond() {
	sed -i '/appfilter/d' /etc/crontabs/root 2>/dev/null
	autoupdate=`uci -q get appfilter.global.autoupdate 2>/dev/null`
	[ "$autoupdate" == 1 ] || return 1
	updatetime=`uci -q get appfilter.global.update_time  | awk -F ':' '{print $2" "$1}'` || updatetime="30 04"
	echo "$updatetime * * * /usr/bin/appfilterupdate " >> /etc/crontabs/root
}

service_triggers()
{
	procd_add_reload_trigger "appfilter"
}

stop_service(){
	killall -9 oafd
	rmmod oaf
}

start_service(){
	oafenable=$(uci -q get appfilter.global.enable)
	if [ "x$oafenable" == "x1" ] ;then

	test -f $FEATURE_FILE && rm $FEATURE_FILE
	test -f $CLASS_FILE && rm $CLASS_FILE
	add_crond
	rm -rf /tmp/appfilter
	space=$(uci -q get appfilter.global.filter_space)
	if [ $space -eq 1 ];then
		cat  /etc/appfilter/feature_en.cfg > $FEATURE_FILE ; echo "" >> $FEATURE_FILE
	        cat /etc/appfilter/feature.user.cfg >> $FEATURE_FILE ; echo "" >> $FEATURE_FILE
	else
		cat  /etc/appfilter/feature_cn.cfg > $FEATURE_FILE ; echo "" >> $FEATURE_FILE
		cat /etc/appfilter/feature.user.cfg >> $FEATURE_FILE ; echo "" >> $FEATURE_FILE
	fi
	gen_class.sh /tmp/feature.cfg
	insmod oaf
	/usr/bin/oaf_rule reload
	procd_open_instance
	procd_set_param respawn 60 5 5
	procd_set_param stderr 1
	procd_set_param command "$OAFD_BIN"
	procd_close_instance
	else
	  stop_service
	  exit 1
 	fi
}


reload_service() {
	stop
	start
}

