#!/bin/sh
uci set luci.main.lang=zh_cn
uci set system.@system[0].timezone=CST-8
uci set system.@system[0].zonename=Asia/Shanghai
uci set dhcp.@dnsmasq[0].cachesize='10000'
uci set dhcp.@dnsmasq[0].min_ttl='3600'
uci set dhcp.@dnsmasq[0].filter_aaaa='1'
uci set dhcp.@dnsmasq[0].localservice='0'
uci set dhcp.@dnsmasq[0].nonwildcard='0'
uci set dhcp.lan.ra=''
uci set dhcp.lan.ndp=''
uci set dhcp.lan.dhcpv6=''
uci set dhcp.lan.ignore='0'
uci set dhcp.lan.ra_management='1'
uci set dhcp.lan.ra_default='1'
uci set dhcp.lan.force='1'
uci set network.lan.delegate='0'
uci set network.wan.mtu=1460
uci set network.wan.metric='41'
uci set network.wan.delegate='0'
uci set network.wan.ipv6='0'
uci -q delete network.wan6
uci set fstab.@global[0].anon_mount=1
uci set fstab.@global[0].check_fs=1
sed -i '/option disabled/d' /etc/config/wireless
sed -i '/set wireless.radio${devidx}.disabled/d' /lib/wifi/mac80211.sh
uci set wireless.radio0.disabled=0
uci set wireless.radio1.disabled=0
uci set vsftpd.@listen[0].enable4='0'
uci commit vsftpd
uci commit wireless
uci commit luci
uci commit system
uci commit dhcp
uci commit fstab
uci commit network
wifi up

rm -f /usr/lib/lua/luci/view/admin_status/index/ddns.htm
rm -f /usr/lib/lua/luci/view/admin_status/index/upnp.htm
rm -f /usr/lib/lua/luci/view/admin_status/index/minidlna.htm

[ "x$(uci -q get netwizard.netwizard.display)" = "x1"  ] &&  echo ' ' > /etc/config/netwizarded
sed -i 's/\"nas\"/\"services\"/g' /usr/lib/lua/luci/controller/samba4.lua
ln -sf /sbin/ip /usr/bin/ip

# sed -i 's/root::0:0:99999:7:::/root:$1$V4UetPzk$CYXluq4wUazHjmCDBCqXF.:0:0:99999:7:::/g' /etc/shadow
# [ -f '/bin/bash' ] && sed -i 's|root:x:0:0:root:/root:/bin/ash|root:x:0:0:root:/root:/bin/bash|g' /etc/passwd

sed -i 's/immortalwrt.org/openwrt.org/g'  /etc/config/luci

sed -i '/DISTRIB_REVISION/d' /etc/openwrt_release
cat /etc/openwrt_release1 >> /etc/openwrt_release
sed -i '/DISTRIB_DESCRIPTION/d' /etc/openwrt_release
echo "DISTRIB_DESCRIPTION='EzOpWrt '" >> /etc/openwrt_release

sed -i '/REDIRECT --to-ports 53/d' /etc/firewall.user
echo "iptables -t nat -I POSTROUTING -o br-lan -j MASQUERADE" >> /etc/firewall.user
echo 'iptables -I zone_lan_forward -t filter -m conntrack --ctstate DNAT -j ACCEPT' >> /etc/firewall.user
sed -i '/lcp-echo/d' /etc/ppp/options
echo "lcp-echo-failure 10" >>  /etc/ppp/options
echo "lcp-echo-interval 200" >>  /etc/ppp/options
sed -i '/log-facility/d' /etc/dnsmasq.conf
echo "log-facility=/dev/null" >> /etc/dnsmasq.conf

sed -i 's/cbi.submit\"] = true/cbi.submit\"] = \"1\"/g' /usr/lib/lua/luci/dispatcher.lua
echo 'hsts=0' > /root/.wgetrc
rm -rf /tmp/luci-*

exit 0
