#!/bin/sh
touch /etc/config/base_config
uci -q get base_config.@base[0] >/dev/null 2>&1 || uci add base_config base >/dev/null 2>&1
ver=$(uci -q get base_config.@base[0].ver 2>/dev/null)
test -n "$ver" || ver=0
setup_ssid()
{
    local r="$1"
    if ! uci show wireless.${r} >/dev/null 2>&1; then
        return
    fi
    SUBFIX=`echo -n $MACADDR | sed 's/://g' | tr a-z A-Z | tail -c4`
    SSID=${DISTRIB_ID}_${SUBFIX}
    logger "default-wifi: set $1 -- ssid:${SSID} -- password:${SSID_PASSWD}"
    # local s="wlan$1"
    #local mac=`ifconfig ${s} | grep "HWaddr" | awk '{print $5}'`
    #local wifimac=`echo ${mac}|awk -F ":" '{print $4""$5""$6 }'|tr A-Z a-z|cut -c4-`
    uci -q set wireless.${r}.disabled=0
    uci -q set wireless.${r}.country=CN
    if [ `uci -q get wireless.${r}.channel` -lt 14 ]; then
        uci -q set wireless.${r}.channel=11
        uci -q set wireless.default_${r}.ssid="${SSID}"-2.4G
    else
        uci -q set wireless.${r}.channel=149
        uci -q set wireless.default_${r}.ssid="${SSID}"-5G
    fi
    uci -q set wireless.default_${r}.encryption='psk2'
    uci -q set wireless.default_${r}.key="${SSID_PASSWD}"
    uci commit wireless
}
setup_network()
{
     wan_interface=`uci -q get network.wan.$ifname` 
     a=$(ip address | awk -F ': ' '/eth[0-9]+/ {print $2}' )
     b=$(echo "$a" | wc -l)
     [[ ${b} -gt 1 ]] && {
	  lannet=""
	  for i in $(seq 1 $b) ; do [ "${wan_interface}" = "$(echo "$a" | sed -n ${i}p)" ] || lannet="${lannet} $(echo "$a" | sed -n ${i}p)" ;done
 	  [ "x$ifname" = "xdevice" ] &&  uci -q set network.@$ifname[0].ports="${lannet}"  || uci -q set network.lan.$ifname="${lannet}"
 	  [ `uci -q get network.wan6` ] && uci -q set network.wan6.$ifname="@wan"
     }
}

. /etc/openwrt_release
test -n "${DISTRIB_ID}" || DISTRIB_ID=EzOpWrt
DISTRIB_ID=$(echo -n $DISTRIB_ID | tr a-z A-Z)
uci -q set fstab.@global[0].check_fs=1
ifname=$(uci -q get network.lan.ifname ) 
[ "x$ifname" = "x" ] && ifname="device" || ifname="ifname" 
MACADDR=""
test -e /usr/share/natcapd/board_mac.lua && MACADDR=$(lua /usr/share/natcapd/board_mac.lua)
test -n "$MACADDR" || MACADDR=$(. /lib/functions/system.sh; get_mac_label | tr a-f A-F)
test -n "$MACADDR" || MACADDR=$(cat /etc/board.json | jsonfilter -e "$['network']['wan']['macaddr']" | tr a-f A-F)
test -n "$MACADDR" || MACADDR=$(cat /etc/board.json | jsonfilter -e "$['network']['lan']['macaddr']" | tr a-f A-F)
test -n "$MACADDR" || MACADDR=$(cat /sys/class/net/eth0/address | tr a-f A-F)
test -n "$MACADDR" || MACADDR=$(cat /sys/class/net/eth1/address | tr a-f A-F)
test -n "$MACADDR" || MACADDR=$(head -c6 /dev/urandom | hexdump -e '/1 "%02X:"' | head -c17)
test -n "$MACADDR" || MACADDR=$(head -c6 /dev/random | hexdump -e '/1 "%02X:"' | head -c17)

test $ver -lt 1 && {
    SSID_PASSWD=88888888

    if [ `find /sys/class/net/ -name wlan* | wc -l` -gt 0 ]; then
      for i in radio0 radio1 radio2 radio3 wifi0 wifi1 wifi2 wifi3; do
            setup_ssid ${i}
        done
    fi
    sed -i '/option disabled/d' /etc/config/wireless  >/dev/null 2>&1
    sed -i '/set wireless.radio${devidx}.disabled/d' /lib/wifi/mac80211.sh   >/dev/null 2>&1
    wifi up
    setup_network
    sed -i '/lcp-echo/d' /etc/ppp/options
    echo "lcp-echo-failure 10" >>  /etc/ppp/options 
    echo "lcp-echo-interval 200" >>  /etc/ppp/options
    ver=1
    uci -q set base_config.@base[0].base$ver=$ver
}
test $ver -lt 2 && {
frmware=`cat /etc/ezopenwrt_version | awk -F '-' '{printf $2}'`

	[ "$(uci -q get dropbear.@dropbear[0] 2>/dev/null)" = "dropbear" ] && {
		uci -q set dropbear.@dropbear[0].PasswordAuth='on'
		uci -q set dropbear.@dropbear[0].RootPasswordAuth='on'
		uci -q set dropbear.@dropbear[0].Port='22'
		uci -q set dropbear.@dropbear[0].Interface='lan'
		uci commit dropbear
		touch /etc/dropbear/authorized_keys && chmod 600 /etc/dropbear/authorized_keys
	}

uci -q batch <<-EOF
set luci.main.lang='zh_cn'
set luci.main.mediaurlbase='/luci-static/kucat'
set system.@system[0].timezone=CST-8
set system.@system[0].zonename=Asia/Shanghai
set system.@system[0].ttylogin='1'
delete system.ntp.server
add_list system.ntp.server='time1.cloud.tencent.com'
add_list system.ntp.server='ntp1.aliyun.com'
add_list system.ntp.server='ntp.ntsc.ac.cn'
add_list system.ntp.server='cn.ntp.org.cn'
set dhcp.@dnsmasq[0].cachesize='10000'
set dhcp.@dnsmasq[0].min_ttl='3600'
set dhcp.@dnsmasq[0].filter_aaaa='0'
set dhcp.@dnsmasq[0].localservice='0'
set dhcp.@dnsmasq[0].nonwildcard='0'
set dhcp.@dnsmasq[0].port='53'
set fstab.@global[0].anon_mount=1
set fstab.@global[0].check_fs=1
set vsftpd.@listen[0].enable4='0'
set upnpd.config.enabled='0'
set upnpd.config.igdv1='1'
set mwan3.wan.enabled='0'
EOF
	[ "$(uci -q get firewall.@zone[0].name 2>/dev/null)" = "lan" ] && {
		[ "$(uci -q get firewall.@zone[0].mtu_fix 2>/dev/null)" = "1" ] || uci -q set firewall.@zone[0].mtu_fix='1'
	}
if [ $frmware = plus ] ;then
uci -q batch <<-EOF
set dhcp.lan.ndp=''
set dhcp.lan.ra='hybrid'
set dhcp.lan.dhcpv6='hybrid'
set dhcp.lan.ignore='0'
set dhcp.lan.ra_management='1'
set dhcp.lan.ra_default='1'
set dhcp.lan.force='1'
set network.lan.delegate='0'
set network.wan.mtu=1420
set network.wan.metric='41'
set network.wan.delegate='0'
set network.wan.ipv6='auto'
set turboacc.config.fullcone_nat='1'
set turboacc.config.bbr_cca='0'
set turboacc.config.sfe_flow='0'
set turboacc.config.hw_flow='0'
set turboacc.config.sw_flow='0'

EOF

sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/aria2.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/view/aria2/overview_status.htm
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/hd_idle.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/samba4.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/minidlna.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/transmission.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/mjpg-streamer.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/p910nd.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/usb_printer.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/xunlei.lua
sed -i 's/services/nas/g'  /usr/lib/lua/luci/view/minidlna_status.htm
elif  [ $frmware = bypass ] ;then
uci -q batch <<-EOF
set dhcp.lan.ra=''
set dhcp.lan.ndp=''
set dhcp.lan.dhcpv6=''
set dhcp.lan.ignore='0'
set dhcp.lan.ra_management='1'
set dhcp.lan.ra_default='1'
set dhcp.lan.force='1'
set network.lan.delegate='0'
set network.wan.mtu=1420
set network.wan.metric='41'
set network.wan.delegate='0'
set network.wan.ipv6='0'
-q delete network.wan6
set turboacc.config.sw_flow='0'
EOF
sed -i 's/\"nas\"/\"services\"/g' /usr/lib/lua/luci/controller/samba4.lua
else
uci -q batch <<-EOF
set dhcp.lan.ra='hybrid'
set dhcp.lan.dhcpv6='hybrid'
set dhcp.lan.ndp=''
set dhcp.lan.ignore='0'
set dhcp.lan.ra_management='1'
set dhcp.lan.ra_default='1'
set dhcp.lan.force='1'
set network.lan.delegate='0'
set network.wan.mtu=1420
set network.wan.metric='41'
set network.wan.delegate='0'
set network.wan.ipv6='auto'
set turboacc.config.sw_flow='0'
EOF
sed -i 's/\"nas\"/\"services\"/g' /usr/lib/lua/luci/controller/samba4.lua
fi
if ! uci -q get system.@imm_init[0].lang > "/dev/null"; then
	uci -q set luci.main.lang="auto"
	uci -q set system.@imm_init[0].lang="1"
fi
if ! uci -q get system.@imm_init[0].anon_mount > "/dev/null"; then
	uci -q set fstab.@global[0].anon_mount="1"
	uci -q commit fstab
	uci -q set system.@imm_init[0].anon_mount="1"
fi
uci -q set firewall.@defaults[0].fullcone='1'
[ $(grep -c shortcut_fe /etc/config/firewall) -eq '0' ] && uci -q  set firewall.@defaults[0].flow_offloading='1'
uci -q  set firewall.@defaults[0].input='ACCEPT'
uci -q get system.@imm_init[0] > "/dev/null" || uci -q add system imm_init > "/dev/null"
uci -q  set dropbear.@dropbear[0].Interface='lan'
uci commit dropbear
uci commit vsftpd
uci commit luci
uci commit fstab
uci commit upnpd
uci commit dhcp
uci commit fstab
uci commit turboacc
uci commit network
uci commit system
uci commit firewall
uci commit mwan3
/etc/init.d/miniupnpd restart
/etc/init.d/turboacc restart
/etc/init.d/ttyd restart
/etc/init.d/mwan3 restart

rm -f /usr/lib/lua/luci/view/admin_status/index/ddns.htm
rm -f /usr/lib/lua/luci/view/admin_status/index/minidlna.htm
rm -f /usr/lib/lua/luci/view/admin_status/index/mwan.htm
rm -f /usr/lib/lua/luci/view/admin_status/index/upnp.htm
rm -f /usr/lib/lua/luci/view/admin_status/index/ddns.htm
ver=2
uci -q  set base_config.@base[0].base$ver=$ver
}
test $ver -lt 3 && {
# kB
memtotal=$(grep MemTotal /proc/meminfo | awk '{print $2}')
cachesize=2048
dnsforwardmax=2048
nf_conntrack_max=16384
if test $memtotal -ge 1048576; then
	# > 1024M
	cachesize=10000
	dnsforwardmax=10000
	nf_conntrack_max=524288
elif test $memtotal -ge 524288; then
	# <= 1024M
	cachesize=10000
	dnsforwardmax=10000
	nf_conntrack_max=262144
elif test $memtotal -ge 262144; then
	# <= 512M
	cachesize=8192
	dnsforwardmax=8192
	nf_conntrack_max=131072
elif test $memtotal -ge 131072; then
	# <= 256M
	cachesize=4096
	dnsforwardmax=4096
	nf_conntrack_max=65536
elif test $memtotal -ge 65536; then
	# <= 128M
	cachesize=2048
	dnsforwardmax=2048
	nf_conntrack_max=32768
else
	# < 64M
	cachesize=1024
	dnsforwardmax=1024
	nf_conntrack_max=16384
fi

	uci -q get dhcp.@dnsmasq[0] || uci add dhcp dnsmasq
	uci -q set dhcp.@dnsmasq[0].cachesize="$cachesize"
	uci -q set dhcp.@dnsmasq[0].dnsforwardmax="$dnsforwardmax"
	uci -q set dhcp.@dnsmasq[0].localservice='0'
	uci -q set dhcp.@dnsmasq[0].localise_queries='1'
	uci -q set dhcp.@dnsmasq[0].rebind_protection='0'
	uci -q set dhcp.@dnsmasq[0].rebind_localhost='1'
	uci commit dhcp
	ver=3
uci -q set base_config.@base[0].base$ver=$ver
}

# fix usb auto umount bug
# cp /usr/share/base-config/mount.hotplug /etc/hotplug.d/block/10-mount

#FIXME fixup for openvpn client
uci delete openvpn_recipes.client_tun.pkcs12 2>/dev/null && uci commit openvpn_recipes

#replace wget
test -x /usr/bin/wget && rm -f /bin/wget && ln -s /usr/bin/wget /bin/wget
test -x /usr/bin/vim && touch /root/.vimrc

#clean all log if new flash firmware
mount -t pstore -o noatime pstore /sys/fs/pstore 2>/dev/null
rm -f /sys/fs/pstore/*

#usb fixup
test -f /etc/usb-mode.json && {
	sed -i 's/05c6:9024/05c6:0000/' /etc/usb-mode.json
}
#update /etc/hosts
grep -q services.googleapis.cn /etc/hosts || echo 142.250.204.35 services.googleapis.cn >>/etc/hosts
grep -q google.cn /etc/hosts || echo 142.250.66.131 google.cn >>/etc/hosts

#usb fixup
test -f /etc/usb-mode.json && {
	sed -i 's/05c6:9024/05c6:0000/' /etc/usb-mode.json
}

test $ver -lt 4 && {
	uci -q set ucitrack.@fstab[0].exec='/sbin/block mount'
	uci commit ucitrack
	ver=4
uci -q set base_config.@base[0].base$ver=$ver
}


echo 'iptables -I zone_lan_forward -t filter -m conntrack --ctstate DNAT -j ACCEPT' >> /etc/firewall.user
sed -i '/coremark/d' /etc/crontabs/root

ln -sf /sbin/ip /usr/bin/ip

# Disable opkg signature check
sed -i 's/option check_signature/# option check_signature/g' /etc/opkg.conf

new_DISTRIB_REVISION=`cat  /etc/ezopenwrt_version`

if [ ` cat /etc/config/luci | grep immortalwrt` ] ;then 

[ -f /etc/ezopenwrt_version ]  && { 
    sed -i '/DISTRIB_DESCRIPTION/d' /etc/openwrt_release
    new_DISTRIB_REVISION=`cat  /etc/ezopenwrt_version`
    echo "DISTRIB_DESCRIPTION='EzOpWrt "${new_DISTRIB_REVISION}"'" >> /etc/openwrt_release
}

    sed -i 's/immortalwrt/openwrt/g' /etc/config/luci
    # opkg mirror
    sed -i 's,downloads.immortalwrt.org,mirrors.vsean.net/openwrt,g' /etc/opkg/distfeeds.conf
    # sed -i 's,downloads.immortalwrt.org,mirrors.vsean.net/openwrt,g' /etc/opkg/distfeeds.conf
else
sed -i '/DISTRIB_DESCRIPTION/d' /etc/openwrt_release
echo "DISTRIB_DESCRIPTION='OpenWrt '" >> /etc/openwrt_release
[ -f /etc/ezopenwrt_version ]  && { 
    sed -i '/DISTRIB_REVISION/d' /etc/openwrt_release
    echo "DISTRIB_REVISION=' "${new_DISTRIB_REVISION}"'" >> /etc/openwrt_release
}

# sed -i 's,downloads.openwrt.org,mirror.sjtu.edu.cn/openwrt,g' /etc/opkg/distfeeds.conf
sed -i 's#downloads.openwrt.org#mirrors.cloud.tencent.com/lede#g' /etc/opkg/distfeeds.conf
sed -i "s/# //g" /etc/opkg/distfeeds.conf
sed -i '/openwrt_luci/ { s/snapshots/releases\/18.06.9/g; }'  /etc/opkg/distfeeds.conf

fi
test $ver -lt 5 && {
	rm -f /etc/nginx/conf.d/_lan.crt  /etc/nginx/conf.d/_lan.key
	test -e /etc/nginx/conf.d/_lan.conf && \
	/usr/bin/nginx-util 'add_ssl' '_lan'
	ver=5
uci -q set base_config.@base[0].base$ver=$ver
}
# set dockerd.globals if exist
test $version -lt 6 && {
	uci -q get dockerd.globals 2>/dev/null && {
		uci -q set dockerd.globals.data_root='/opt/docker/'
		uci -q set dockerd.globals.auto_start='0'
		uci commit dockerd
	}
	version=6
uci -q set base_config.@base[0].base$ver=$ver
}
uci -q set base_config.@base[0].ver=$ver
uci commit base_config
ntpd -n -q -p 1.lede.pool.ntp.org
sed -i '/log-facility/d' /etc/dnsmasq.conf
echo "log-facility=/dev/null" >> /etc/dnsmasq.conf
echo 'hsts=0' > /root/.wgetrc
rm -rf /tmp/luci-*

exit 0
