#!/bin/sh
[ -f '/etc/rpcd_19_cpu.js' ] &&	mv -f '/etc/rpcd_19_cpu.js' '/www/luci-static/resources/view/status/include/19_cpu.js'
[ -f '/etc/rpcd_28_ethinfo.js' ] &&mv -f '/etc/rpcd_28_ethinfo.js' '/www/luci-static/resources/view/status/include/28_ethinfo.js'
[ -f '/etc/rpcd_10_system.js' ] && mv -f '/etc/rpcd_10_system.js' '/www/luci-static/resources/view/status/include/10_system.js'
[ -f '/etc/rpcd_29_ports.js' ] && mv -f '/etc/rpcd_29_ports.js' '/www/luci-static/resources/view/status/include/29_ports.js'
[ ! -f '/etc/rpcd_luci' ] || \
	mv -f '/etc/rpcd_luci' '/usr/libexec/rpcd/luci'
[ -f '/www/luci-static/resources/view/status/include/21_ethinfo.js' ] && rm -rf /www/luci-static/resources/view/status/include/21_ethinfo.js
/etc/init.d/rpcd restart
exit 0
