#!/bin/bash /etc/rc.common

START=86
NAME=netspeedlimit
dev=br-lan

del_rule() {
	tc qdisc del dev $dev root 2>/dev/null
	tc qdisc del dev $dev ingress 2>/dev/null
	tc qdisc del dev ${dev}-ifb root 2>/dev/null
	ip link del dev ${dev}-ifb 2>/dev/null
	for face in $( tc qdisc show | grep htb | awk '{print $5}');do
	    tc qdisc del dev $face root
	done
	iptables -t mangle -F PREROUTING 2>/dev/null
}


add_dev() {
	ip link add dev ${dev}-ifb name ${dev}-ifb type ifb
	ip link set dev ${dev}-ifb up
	
	tc qdisc add dev $dev root handle 1: htb default 1
	tc class add dev $dev parent 1: classid 1:1 htb rate 10000Mbit
	
	tc qdisc add dev ${dev}-ifb root handle 1: htb default 2
	tc class add dev ${dev}-ifb parent 1: classid 1:1 htb rate 10000Mbit
	tc qdisc add dev $dev ingress
	tc filter add dev $dev parent ffff: protocol ip u32 match u32 0 0 flowid 1:1 action mirred egress redirect dev ${dev}-ifb
}
add_mac() {
	mac="-m mac --mac-source $mac"
	id=$1
	if [ "$UL" -gt 0 ]; then
	       tc class add dev ${dev}-ifb parent 1:1 classid 1:2"$id" htb rate "$UL"kbit prio 1
	       tc qdisc add dev ${dev}-ifb parent 1:2"$id" handle 2"$id": pfifo
	       tc filter add dev ${dev}-ifb parent 1:0 protocol ip prio 100 handle 2$id fw flowid 1:2"$id"
	fi
	if [ "$DL" -gt 0 ]; then
	       tc class add dev ${dev} parent 1:1 classid 1:2"$id" htb rate "$DL"kbit prio 1
	       tc qdisc add dev ${dev} parent 1:2"$id" handle 2"$id": pfifo
	       tc filter add dev ${dev} parent 1:0 protocol ip prio 100 handle 2$id fw flowid 1:2"$id" 
	fi

	[ "$DL" -gt 0 ] || [ "$UL" -gt 0 ] && iptables -t mangle -A PREROUTING $mac $WT -j MARK --set-mark 2$id
 
	id=`expr $id + 1 `

}



add_ip() {
	id=$1
	if [ "$UL" -gt 0 ]; then
	       tc class add dev ${dev}-ifb parent 1:1 classid 1:2"$id" htb rate "$UL"kbit prio 1
	       tc qdisc add dev ${dev}-ifb parent 1:2"$id" handle 100"$id": pfifo
	       tc filter add dev ${dev}-ifb parent 1:0 protocol ip prio 100 handle 2$id fw flowid 1:2"$id"
	fi
	if [ "$DL" -gt 0 ]; then
	       tc class add dev ${dev} parent 1:1 classid 1:2"$id" htb rate "$DL"kbit prio 1
	       tc qdisc add dev ${dev} parent 1:2"$id" handle 100"$id": pfifo
	       tc filter add dev ${dev} parent 1:0 protocol ip prio 100 handle 2$id fw flowid 1:2"$id"
	fi
	if [ "$DL" -gt 0 ] || [ "$UL" -gt 0 ] ; then
		 if [ -n `echo $mac | grep '-' ` ]; then
	        	mac=`echo $mac | awk -F '[.-]' '{if ($5=="") print $1"."$2"."$3"."$4 ; else if ($8=="" && $4<$5) print $1"."$2"."$3"."$4"-"$1"."$2"."$3"."$5 ; else if ($8=="" && $4>$5) print $1"."$2"."$3"."$5"-"$1"."$2"."$3"."$4 ; else if ($8>$4) print $1"."$2"."$3"."$4"-"$1"."$2"."$3"."$8 ; else if ($8<$4) print $1"."$2"."$3"."$8"-"$1"."$2"."$3"."$4}' `
	        	iptables -t mangle -A PREROUTING -m iprange --dst-range "$mac" $WT -j MARK --set-mark 2"$id"
	        	iptables -t mangle -A PREROUTING -m iprange --src-range "$mac" $WT -j MARK --set-mark 2"$id"
	        	iptables -t mangle -A PREROUTING -m iprange --dst-range "$mac" -j RETURN
	        	iptables -t mangle -A PREROUTING -m iprange --src-range "$mac" -j RETURN
	       else
	        	iptables -t mangle -A PREROUTING -s "$mac" $WT -j MARK --set-mark 2"$id"
	        	iptables -t mangle -A PREROUTING -d "$mac" $WT -j MARK --set-mark 2"$id"
	        	iptables -t mangle -A PREROUTING -d "$mac" -j RETURN
	        	iptables -t mangle -A PREROUTING -s "$mac" -j RETURN
	       fi
	fi
	id=`expr $id + 1 `
}

start() {
	[ -f /var/lock/$NAME ] && exit
	if [ "$(grep -c 'option enable .1.' /etc/config/$NAME 2>/dev/null)" -gt "0" ]; then
		touch /var/lock/$NAME
		localip=$(uci get network.lan.ipaddr 2>/dev/null | awk -F '.' '{print $1"."$2"."$3".0/24"}')
		del_rule
		add_dev
		idlist=`uci show $NAME | grep "enable='1'" | grep "device" | grep -oE '\[.*?\]' | grep -o '[0-9]'`
		id=10
		echo start $idlist
		for i in $idlist ;do
				mac=$(uci -q get $NAME.@device[$i].mac )
				DL=$(uci -q get $NAME.@device[$i].download 2>/dev/null | awk '{print $1*8*10^3}')
				UL=$(uci -q get $NAME.@device[$i].upload   2>/dev/null | awk '{print $1*8*10^3}')
				timestart=$(uci -q get $NAME.@device[$i].timestart 2>/dev/null) || timestart="00:00"
				timeend=$(uci -q get $NAME.@device[$i].timeend 2>/dev/null) ||  timeend="00:00"
				wweek=$(uci get $NAME.@device[$i].week  |sed 's/ /,/g' 2>/dev/null)
				[ -z "$timestart" -o -z "$timeend" -o "$timestart" = "$timeend" ] && TIME="" || TIME="--timestart ${timestart} --timestop ${timeend}"
				[ -z "$wweek" -o "$wweek" = "*" ] && WEEK="" || WEEK="--weekdays ${wweek}"
				[ -n "$TIME" -o -n "$WEEK" ] && WT="-m time --kerneltz ${TIME} ${WEEK}" || WT=""
				egrep -q "([A-Fa-f0-9]{2}[-:]){5}[A-Fa-f0-9]{2}" <<< "$mac" && (add_mac $i; :;) || (egrep -q "(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])" <<< "$mac" && add_ip $i)

		done
		rm -f /var/lock/$NAME
	fi
}

stop() {
	rm -f /var/lock/$NAME 2>/dev/null
	del_rule
}

restart() {
	stop
	start
}
